# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/projet/Basys-3-Master.xdc

# Block Designs: bd/central_design/central_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design || ORIG_REF_NAME==central_design} -quiet] -quiet

# IP: bd/central_design/ip/central_design_microblaze_0_0/central_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_microblaze_0_0 || ORIG_REF_NAME==central_design_microblaze_0_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_dlmb_v10_0/central_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_dlmb_v10_0 || ORIG_REF_NAME==central_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_ilmb_v10_0/central_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_ilmb_v10_0 || ORIG_REF_NAME==central_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_dlmb_bram_if_cntlr_0/central_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==central_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_ilmb_bram_if_cntlr_0/central_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==central_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_lmb_bram_0/central_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_lmb_bram_0 || ORIG_REF_NAME==central_design_lmb_bram_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_xbar_0/central_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_xbar_0 || ORIG_REF_NAME==central_design_xbar_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_microblaze_0_axi_periph_0/central_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==central_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_microblaze_0_axi_intc_0/central_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==central_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_microblaze_0_xlconcat_0/central_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==central_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_mdm_1_0/central_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_mdm_1_0 || ORIG_REF_NAME==central_design_mdm_1_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_clk_wiz_1_0/central_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_clk_wiz_1_0 || ORIG_REF_NAME==central_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_rst_clk_wiz_1_100M_0/central_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==central_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_axi_gpio_0_0/central_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_axi_gpio_0_0 || ORIG_REF_NAME==central_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_axi_gpio_1_0 || ORIG_REF_NAME==central_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/central_design/ip/central_design_myip_0_0/central_design_myip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==central_design_myip_0_0 || ORIG_REF_NAME==central_design_myip_0_0} -quiet] -quiet

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/central_design_ooc.xdc
