# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.srcs/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0.xci
# IP: The module: 'central_design_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.srcs/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0.xci
# IP: The module: 'central_design_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Rockefeller157/Desktop/VHDL/FPGA-M1/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_axi_gpio_1_0/central_design_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
