# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Central_DCC/Central_DCC/Central_DCC.srcs/sources_1/bd/central_design/ip/central_design_ilmb_bram_if_cntlr_0/central_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'central_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_ilmb_bram_if_cntlr_0/central_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Central_DCC/Central_DCC/Central_DCC.srcs/sources_1/bd/central_design/ip/central_design_ilmb_bram_if_cntlr_0/central_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'central_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Central_DCC/Central_DCC/Central_DCC.gen/sources_1/bd/central_design/ip/central_design_ilmb_bram_if_cntlr_0/central_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'central_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
